version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
    post_install:
      - poetry install --with docs

sphinx:
  configuration: docs/source/conf.py