version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
