name: on-pull-request
on: [pull_request]
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: $${{ matrix.os }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          version: "1.4.2"
      - name: Install package
        run: poetry install
      - name: Lint (black)
        run: poetry run black . --check
      - name: Lint (isort)
        run: poetry run isort . --check
      - name: Lint (ruff)
        run: poetry run ruff mfglib tests
      - name: Lint (mypy)
        run: poetry run mypy
      - name: Test (pytest)
        run: poetry run pytest
      - name: Docs (sphinx)
        run: poetry run sphinx-build -EW docs/source docs/build
