name: on-pr
on:
  pull_request
jobs:
  lint:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: snok/install-poetry@v1
      - run: |
          poetry --version
          poetry install
          poetry run black . --check
          poetry run isort . --check
          poetry run ruff check mfglib tests
          poetry run mypy --python-version 3.9
          poetry run mypy --python-version 3.10
          poetry run mypy --python-version 3.11
          poetry run mypy --python-version 3.12
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ matrix.os }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - run: |
          poetry --version
          poetry install
          poetry run pytest -x --durations 5
